-- CBS Support database migration
-- Version: 202608071000_create_security_audit_events
-- Purpose: common append-only, privacy-conscious security audit ledger.
-- Preconditions: digital schema and the application role exist.
-- migration-transaction: true
-- Rollback/forward-fix: audit records are compliance evidence. Do not drop or
-- rewrite this table after deployment. Correct behavior with a forward migration.

CREATE TABLE digital.security_audit_events (
    audit_id bigint GENERATED BY DEFAULT AS IDENTITY,
    tenant_id bigint,
    actor_kind varchar(16) NOT NULL,
    actor_user_id bigint,
    target_kind varchar(32),
    target_id varchar(128),
    action varchar(64) NOT NULL,
    outcome varchar(16) NOT NULL,
    occurred_at timestamptz NOT NULL DEFAULT now(),
    correlation_id varchar(128),
    ip_prefix varchar(64),
    source_context jsonb NOT NULL DEFAULT '{}'::jsonb,
    details jsonb NOT NULL DEFAULT '{}'::jsonb,
    CONSTRAINT pk_security_audit_events PRIMARY KEY (audit_id),
    CONSTRAINT ck_security_audit_events_actor_kind
        CHECK (actor_kind IN ('Anonymous', 'Admin', 'Client', 'System')),
    CONSTRAINT ck_security_audit_events_actor
        CHECK ((actor_kind IN ('Anonymous', 'System') AND actor_user_id IS NULL)
            OR (actor_kind IN ('Admin', 'Client') AND actor_user_id > 0)),
    CONSTRAINT ck_security_audit_events_tenant
        CHECK (tenant_id IS NULL OR tenant_id > 0),
    CONSTRAINT ck_security_audit_events_action
        CHECK (btrim(action) <> ''),
    CONSTRAINT ck_security_audit_events_outcome
        CHECK (outcome IN ('Success', 'Failure', 'Denied', 'Throttled', 'Error')),
    CONSTRAINT ck_security_audit_events_target
        CHECK ((target_kind IS NULL AND target_id IS NULL)
            OR (target_kind IS NOT NULL AND target_id IS NOT NULL)),
    CONSTRAINT ck_security_audit_events_source_object
        CHECK (jsonb_typeof(source_context) = 'object'),
    CONSTRAINT ck_security_audit_events_details_object
        CHECK (jsonb_typeof(details) = 'object'),
    CONSTRAINT ck_security_audit_events_correlation
        CHECK (correlation_id IS NULL OR btrim(correlation_id) <> '')
);

CREATE INDEX ix_security_audit_events_tenant_occurred
ON digital.security_audit_events (tenant_id, occurred_at DESC, audit_id DESC);

CREATE INDEX ix_security_audit_events_action_occurred
ON digital.security_audit_events (action, occurred_at DESC, audit_id DESC);

CREATE OR REPLACE FUNCTION digital.prevent_security_audit_event_mutation()
RETURNS trigger
LANGUAGE plpgsql
AS $function$
BEGIN
    RAISE EXCEPTION 'digital.security_audit_events is append-only'
        USING ERRCODE = '42501';
END;
$function$;

CREATE TRIGGER trg_security_audit_events_append_only
BEFORE UPDATE OR DELETE ON digital.security_audit_events
FOR EACH ROW
EXECUTE FUNCTION digital.prevent_security_audit_event_mutation();

REVOKE ALL ON TABLE digital.security_audit_events FROM PUBLIC;
REVOKE ALL ON SEQUENCE digital.security_audit_events_audit_id_seq FROM PUBLIC;

-- The application role may append and, for the Admin-only review endpoint,
-- read records. It cannot update, delete, truncate, disable the trigger, or
-- change ownership. Production must use a separate migration/owner role; an
-- optional cbs_support_audit_owner role is adopted below when provisioned.
DO $application_role$
BEGIN
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'shovan') THEN
        GRANT SELECT, INSERT ON TABLE digital.security_audit_events TO shovan;
        GRANT USAGE ON SEQUENCE digital.security_audit_events_audit_id_seq TO shovan;
        REVOKE UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER
            ON TABLE digital.security_audit_events FROM shovan;
    END IF;

    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'cbs_support_audit_owner') THEN
        ALTER TABLE digital.security_audit_events OWNER TO cbs_support_audit_owner;
        ALTER FUNCTION digital.prevent_security_audit_event_mutation() OWNER TO cbs_support_audit_owner;
    END IF;
END
$application_role$;

COMMENT ON TABLE digital.security_audit_events IS
    'Append-only security audit evidence. No passwords, tokens, cookies, authorization headers, request bodies, message bodies, raw exceptions, or full IP addresses are stored.';
COMMENT ON COLUMN digital.security_audit_events.ip_prefix IS
    'Masked network prefix only: IPv4 /24 or IPv6 /64. Retention and deletion are controlled by the operational audit-retention role.';
COMMENT ON COLUMN digital.security_audit_events.source_context IS
    'Small allow-listed transport metadata object; never arbitrary request data.';
COMMENT ON COLUMN digital.security_audit_events.details IS
    'Safe transition metadata only; never secrets, message content, arbitrary payloads, or exception dumps.';
