-- Create append-only Ticket/Inquiry root audit history.
-- Preconditions: 202607261010_modernize_case_conversations has been applied.
-- migration-transaction: true
-- Forward-fix only after application writes begin; audit rows are retained.

CREATE TABLE digital.case_audit (
    audit_id bigint GENERATED BY DEFAULT AS IDENTITY,
    case_id bigint NOT NULL,
    case_type varchar(16) NOT NULL,
    client_id bigint NOT NULL,
    actor_user_id bigint,
    actor_type varchar(16) NOT NULL,
    action varchar(64) NOT NULL,
    previous_version bigint NOT NULL,
    resulting_version bigint NOT NULL,
    occurred_at timestamptz NOT NULL DEFAULT now(),
    changed_fields jsonb NOT NULL DEFAULT '{}'::jsonb,
    correlation_id varchar(128),
    is_system_generated boolean NOT NULL DEFAULT FALSE,
    CONSTRAINT pk_case_audit PRIMARY KEY (audit_id),
    CONSTRAINT fk_case_audit_case
        FOREIGN KEY (case_id) REFERENCES digital.instructions(id),
    CONSTRAINT ck_case_audit_type
        CHECK (case_type IN ('Ticket', 'Inquiry')),
    CONSTRAINT ck_case_audit_actor_type
        CHECK (actor_type IN ('Admin', 'Client', 'System')),
    CONSTRAINT ck_case_audit_actor
        CHECK (
            (actor_type = 'System' AND actor_user_id IS NULL)
            OR (actor_type IN ('Admin', 'Client') AND actor_user_id > 0)),
    CONSTRAINT ck_case_audit_generation_source
        CHECK (is_system_generated = (actor_type = 'System')),
    CONSTRAINT ck_case_audit_action_nonempty
        CHECK (btrim(action) <> ''),
    CONSTRAINT ck_case_audit_versions
        CHECK (previous_version >= 0 AND resulting_version = previous_version + 1),
    CONSTRAINT ck_case_audit_changed_fields_object
        CHECK (jsonb_typeof(changed_fields) = 'object'),
    CONSTRAINT ck_case_audit_correlation_nonempty
        CHECK (correlation_id IS NULL OR btrim(correlation_id) <> '')
);

CREATE INDEX ix_case_audit_case_occurred
ON digital.case_audit (case_id, occurred_at DESC, audit_id DESC);

CREATE INDEX ix_case_audit_client_occurred
ON digital.case_audit (client_id, occurred_at DESC, audit_id DESC);

CREATE OR REPLACE FUNCTION digital.prevent_case_audit_mutation()
RETURNS trigger
LANGUAGE plpgsql
AS $function$
BEGIN
    RAISE EXCEPTION 'digital.case_audit is append-only'
        USING ERRCODE = '42501';
END;
$function$;

CREATE TRIGGER trg_case_audit_append_only
BEFORE UPDATE OR DELETE ON digital.case_audit
FOR EACH ROW
EXECUTE FUNCTION digital.prevent_case_audit_mutation();

REVOKE ALL ON TABLE digital.case_audit FROM PUBLIC;
REVOKE ALL ON SEQUENCE digital.case_audit_audit_id_seq FROM PUBLIC;

-- Grant only the privileges required by the write path.
DO $application_role$
BEGIN
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'shovan') THEN
        GRANT INSERT ON TABLE digital.case_audit TO shovan;
        GRANT USAGE ON SEQUENCE digital.case_audit_audit_id_seq TO shovan;
        REVOKE UPDATE, DELETE, TRUNCATE ON TABLE digital.case_audit FROM shovan;
    END IF;
END
$application_role$;

COMMENT ON TABLE digital.case_audit IS
    'Append-only Ticket/Inquiry mutation history. changed_fields records field names and safe transition metadata only; it excludes case text, remarks, secrets, and full entity snapshots.';
COMMENT ON COLUMN digital.case_audit.correlation_id IS
    'Optional server-generated trace/activity identifier; never an authorization header, token, or exception payload.';
