-- CBS Support database migration
-- Version: 202607221110_create_messaging_v2_schema
-- Purpose: Add Messaging V2 sequence/idempotency columns and owned access,
--          cursor, transactional outbox, and audit tables.
-- Owned objects: the listed digital tables, their constraints, and two columns on
--                digital.instructions. Referenced identity tables are not modified.
-- Preconditions:
--   1. 202607221000_canonical_instruction_client_principal has been applied.
--   2. 202607221100_verify_messaging_v2_readiness.sql has been reviewed.
-- migration-transaction: true
-- Transactional: Yes.
-- Rollback/forward-fix: These durable tables must not be dropped after application
-- writes begin. Correct defects with a new ordered forward-fix migration.

ALTER TABLE digital.instructions
    ADD COLUMN client_message_id uuid,
    ADD COLUMN conversation_sequence bigint;

COMMENT ON COLUMN digital.instructions.client_message_id IS
    'Globally unique caller-generated idempotency key when present; NULL for legacy rows and conversation roots.';

COMMENT ON COLUMN digital.instructions.conversation_sequence IS
    'Monotonic sequence within instruction_id. Empty roots are sequence-0 sentinels; a text-bearing legacy root and replies use positive values.';

CREATE TABLE digital.conversation_access (
    conversation_id bigint NOT NULL,
    client_id bigint NOT NULL,
    conversation_kind varchar(16) NOT NULL,
    state varchar(16) NOT NULL,
    client_user_id integer,
    admin_user_id integer,
    version bigint NOT NULL DEFAULT 1,
    created_at timestamptz NOT NULL DEFAULT now(),
    archived_at timestamptz,
    CONSTRAINT pk_conversation_access PRIMARY KEY (conversation_id),
    CONSTRAINT fk_conversation_access_conversation
        FOREIGN KEY (conversation_id) REFERENCES digital.instructions(id),
    CONSTRAINT fk_conversation_access_client_user
        FOREIGN KEY (client_user_id) REFERENCES internal.support_users(id),
    CONSTRAINT fk_conversation_access_admin_user
        FOREIGN KEY (admin_user_id) REFERENCES admin.users(id),
    CONSTRAINT ck_conversation_access_kind
        CHECK (conversation_kind IN ('Group', 'Private')),
    CONSTRAINT ck_conversation_access_state
        CHECK (state IN ('Active', 'Archived', 'NeedsReview')),
    CONSTRAINT ck_conversation_access_version_positive
        CHECK (version > 0),
    CONSTRAINT ck_conversation_access_archived_timestamp
        CHECK ((state = 'Archived') = (archived_at IS NOT NULL)),
    CONSTRAINT ck_conversation_access_participants
        CHECK (
            (conversation_kind = 'Group'
                AND state = 'Active'
                AND client_user_id IS NULL
                AND admin_user_id IS NULL)
            OR
            (conversation_kind = 'Private'
                AND (
                    (state = 'NeedsReview')
                    OR
                    (state IN ('Active', 'Archived')
                        AND client_user_id IS NOT NULL
                        AND admin_user_id IS NOT NULL)
                ))
        )
);

COMMENT ON TABLE digital.conversation_access IS
    'Authoritative Messaging V2 access metadata. Legacy private roots remain NeedsReview until an administrator confirms both participants.';
COMMENT ON COLUMN digital.conversation_access.client_id IS
    'Tenant copied from the canonical root by a tenant-scoped insert-select; no FK is added to the externally owned client table.';
COMMENT ON COLUMN digital.conversation_access.version IS
    'Optimistic concurrency version incremented on each access-state or participant change.';

CREATE TABLE digital.conversation_sequences (
    conversation_id bigint NOT NULL,
    next_sequence bigint NOT NULL,
    CONSTRAINT pk_conversation_sequences PRIMARY KEY (conversation_id),
    CONSTRAINT fk_conversation_sequences_conversation
        FOREIGN KEY (conversation_id) REFERENCES digital.instructions(id),
    CONSTRAINT ck_conversation_sequences_next_positive
        CHECK (next_sequence >= 1)
);

COMMENT ON TABLE digital.conversation_sequences IS
    'Allocator row locked in the message transaction. next_sequence is max history sequence plus 1 and is at least 1.';

CREATE TABLE digital.conversation_read_cursors (
    read_cursor_id bigint GENERATED BY DEFAULT AS IDENTITY,
    conversation_id bigint NOT NULL,
    principal_kind varchar(16) NOT NULL,
    admin_user_id integer,
    client_user_id integer,
    last_read_sequence bigint NOT NULL DEFAULT 0,
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT pk_conversation_read_cursors PRIMARY KEY (read_cursor_id),
    CONSTRAINT fk_conversation_read_cursors_access
        FOREIGN KEY (conversation_id) REFERENCES digital.conversation_access(conversation_id),
    CONSTRAINT fk_conversation_read_cursors_admin_user
        FOREIGN KEY (admin_user_id) REFERENCES admin.users(id),
    CONSTRAINT fk_conversation_read_cursors_client_user
        FOREIGN KEY (client_user_id) REFERENCES internal.support_users(id),
    CONSTRAINT ck_conversation_read_cursors_principal_kind
        CHECK (principal_kind IN ('Admin', 'Client')),
    CONSTRAINT ck_conversation_read_cursors_principal
        CHECK (
            (principal_kind = 'Admin' AND admin_user_id IS NOT NULL AND client_user_id IS NULL)
            OR
            (principal_kind = 'Client' AND admin_user_id IS NULL AND client_user_id IS NOT NULL)
        ),
    CONSTRAINT ck_conversation_read_cursors_sequence_nonnegative
        CHECK (last_read_sequence >= 0)
);

COMMENT ON TABLE digital.conversation_read_cursors IS
    'Per-principal high-water marks. Separate partial unique indexes enforce one Admin or Client cursor per conversation.';

CREATE TABLE digital.conversation_outbox (
    event_id uuid NOT NULL,
    conversation_id bigint NOT NULL,
    client_id bigint NOT NULL,
    conversation_kind varchar(16) NOT NULL,
    conversation_state varchar(16) NOT NULL,
    client_user_id integer,
    admin_user_id integer,
    access_version bigint NOT NULL,
    message_id bigint,
    event_type varchar(64) NOT NULL,
    schema_version smallint NOT NULL DEFAULT 1,
    payload jsonb NOT NULL,
    occurred_at timestamptz NOT NULL DEFAULT now(),
    available_at timestamptz NOT NULL DEFAULT now(),
    attempt_count integer NOT NULL DEFAULT 0,
    lease_owner varchar(128),
    lease_until timestamptz,
    processed_at timestamptz,
    dead_lettered_at timestamptz,
    last_error_code varchar(64),
    CONSTRAINT pk_conversation_outbox PRIMARY KEY (event_id),
    CONSTRAINT fk_conversation_outbox_access
        FOREIGN KEY (conversation_id) REFERENCES digital.conversation_access(conversation_id),
    CONSTRAINT fk_conversation_outbox_client_user
        FOREIGN KEY (client_user_id) REFERENCES internal.support_users(id),
    CONSTRAINT fk_conversation_outbox_admin_user
        FOREIGN KEY (admin_user_id) REFERENCES admin.users(id),
    CONSTRAINT fk_conversation_outbox_message
        FOREIGN KEY (message_id) REFERENCES digital.instructions(id),
    CONSTRAINT ck_conversation_outbox_event_type_nonempty
        CHECK (btrim(event_type) <> ''),
    CONSTRAINT ck_conversation_outbox_kind
        CHECK (conversation_kind IN ('Group', 'Private')),
    CONSTRAINT ck_conversation_outbox_state
        CHECK (conversation_state IN ('Active', 'Archived', 'NeedsReview')),
    CONSTRAINT ck_conversation_outbox_participants
        CHECK (
            (conversation_kind = 'Group' AND client_user_id IS NULL AND admin_user_id IS NULL)
            OR
            (conversation_kind = 'Private' AND client_user_id IS NOT NULL AND admin_user_id IS NOT NULL)
        ),
    CONSTRAINT ck_conversation_outbox_access_version_positive
        CHECK (access_version > 0),
    CONSTRAINT ck_conversation_outbox_schema_version_positive
        CHECK (schema_version > 0),
    CONSTRAINT ck_conversation_outbox_payload_object
        CHECK (jsonb_typeof(payload) = 'object'),
    CONSTRAINT ck_conversation_outbox_availability_order
        CHECK (available_at >= occurred_at),
    CONSTRAINT ck_conversation_outbox_attempt_nonnegative
        CHECK (attempt_count >= 0),
    CONSTRAINT ck_conversation_outbox_lease_pair
        CHECK ((lease_owner IS NULL) = (lease_until IS NULL)),
    CONSTRAINT ck_conversation_outbox_lease_owner_nonempty
        CHECK (lease_owner IS NULL OR btrim(lease_owner) <> ''),
    CONSTRAINT ck_conversation_outbox_terminal_exclusive
        CHECK (processed_at IS NULL OR dead_lettered_at IS NULL),
    CONSTRAINT ck_conversation_outbox_terminal_not_leased
        CHECK ((processed_at IS NULL AND dead_lettered_at IS NULL)
            OR (lease_owner IS NULL AND lease_until IS NULL)),
    CONSTRAINT ck_conversation_outbox_error_code_nonempty
        CHECK (last_error_code IS NULL OR btrim(last_error_code) <> '')
);

COMMENT ON TABLE digital.conversation_outbox IS
    'Transactional event outbox. Payloads are versioned envelopes and must not contain message bodies or other sensitive content.';

CREATE TABLE digital.conversation_audit (
    audit_id bigint GENERATED BY DEFAULT AS IDENTITY,
    conversation_id bigint NOT NULL,
    client_id bigint NOT NULL,
    action varchar(64) NOT NULL,
    actor_kind varchar(16) NOT NULL,
    admin_user_id integer,
    client_user_id integer,
    occurred_at timestamptz NOT NULL DEFAULT now(),
    details jsonb NOT NULL DEFAULT '{}'::jsonb,
    CONSTRAINT pk_conversation_audit PRIMARY KEY (audit_id),
    CONSTRAINT fk_conversation_audit_access
        FOREIGN KEY (conversation_id) REFERENCES digital.conversation_access(conversation_id),
    CONSTRAINT fk_conversation_audit_admin_user
        FOREIGN KEY (admin_user_id) REFERENCES admin.users(id),
    CONSTRAINT fk_conversation_audit_client_user
        FOREIGN KEY (client_user_id) REFERENCES internal.support_users(id),
    CONSTRAINT ck_conversation_audit_action_nonempty
        CHECK (btrim(action) <> ''),
    CONSTRAINT ck_conversation_audit_actor_kind
        CHECK (actor_kind IN ('Admin', 'Client', 'System')),
    CONSTRAINT ck_conversation_audit_actor
        CHECK (
            (actor_kind = 'Admin' AND admin_user_id IS NOT NULL AND client_user_id IS NULL)
            OR
            (actor_kind = 'Client' AND admin_user_id IS NULL AND client_user_id IS NOT NULL)
            OR
            (actor_kind = 'System' AND admin_user_id IS NULL AND client_user_id IS NULL)
        ),
    CONSTRAINT ck_conversation_audit_details_object
        CHECK (jsonb_typeof(details) = 'object')
);

COMMENT ON TABLE digital.conversation_audit IS
    'Append-only conversation security and lifecycle audit events. details must exclude message bodies and secrets.';
COMMENT ON COLUMN digital.conversation_audit.client_id IS
    'Tenant denormalized for tenant-scoped audit queries; no FK is added to the externally owned client table.';
