-- Add recipient-specific case notifications and outbox idempotency keys.
-- Preconditions: Messaging V2, case modernization, and case audit migrations applied.
-- migration-transaction: true
-- Forward-fix only after application writes begin; retain committed notifications.

ALTER TABLE digital.conversation_outbox
    ADD COLUMN idempotency_key varchar(200);

UPDATE digital.conversation_outbox
SET idempotency_key = 'legacy:' || event_id::text
WHERE idempotency_key IS NULL;

ALTER TABLE digital.conversation_outbox
    ALTER COLUMN idempotency_key SET NOT NULL,
    ADD CONSTRAINT uq_conversation_outbox_idempotency_key UNIQUE (idempotency_key),
    ADD CONSTRAINT ck_conversation_outbox_idempotency_key_nonempty
        CHECK (btrim(idempotency_key) <> '');

CREATE TABLE digital.case_notifications (
    notification_id bigint GENERATED BY DEFAULT AS IDENTITY,
    event_id uuid NOT NULL,
    case_id bigint NOT NULL,
    client_id bigint NOT NULL,
    recipient_kind varchar(16) NOT NULL,
    admin_user_id integer,
    client_user_id integer,
    event_type varchar(64) NOT NULL,
    case_version bigint NOT NULL,
    idempotency_key varchar(240) NOT NULL,
    payload_version smallint NOT NULL DEFAULT 1,
    payload jsonb NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    read_at timestamptz,
    CONSTRAINT pk_case_notifications PRIMARY KEY (notification_id),
    CONSTRAINT fk_case_notifications_event
        FOREIGN KEY (event_id) REFERENCES digital.conversation_outbox(event_id),
    CONSTRAINT fk_case_notifications_case
        FOREIGN KEY (case_id) REFERENCES digital.instructions(id),
    CONSTRAINT fk_case_notifications_admin
        FOREIGN KEY (admin_user_id) REFERENCES admin.users(id),
    CONSTRAINT fk_case_notifications_client
        FOREIGN KEY (client_user_id) REFERENCES internal.support_users(id),
    CONSTRAINT ck_case_notifications_recipient_kind
        CHECK (recipient_kind IN ('Admin', 'Client')),
    CONSTRAINT ck_case_notifications_recipient
        CHECK (
            (recipient_kind = 'Admin' AND admin_user_id IS NOT NULL AND client_user_id IS NULL)
            OR
            (recipient_kind = 'Client' AND client_user_id IS NOT NULL AND admin_user_id IS NULL)
        ),
    CONSTRAINT ck_case_notifications_event_type_nonempty
        CHECK (btrim(event_type) <> ''),
    CONSTRAINT ck_case_notifications_case_version_positive
        CHECK (case_version > 0),
    CONSTRAINT ck_case_notifications_idempotency_nonempty
        CHECK (btrim(idempotency_key) <> ''),
    CONSTRAINT uq_case_notifications_idempotency_key UNIQUE (idempotency_key),
    CONSTRAINT ck_case_notifications_payload_version_positive
        CHECK (payload_version > 0),
    CONSTRAINT ck_case_notifications_payload_object
        CHECK (jsonb_typeof(payload) = 'object')
);

CREATE INDEX ix_case_notifications_client_recipient_created
ON digital.case_notifications (client_id, client_user_id, created_at DESC, notification_id DESC)
WHERE recipient_kind = 'Client';

CREATE INDEX ix_case_notifications_admin_recipient_created
ON digital.case_notifications (admin_user_id, created_at DESC, notification_id DESC)
WHERE recipient_kind = 'Admin';

CREATE OR REPLACE FUNCTION digital.enforce_case_notification_recipient()
RETURNS trigger
LANGUAGE plpgsql
AS $function$
BEGIN
    IF NEW.recipient_kind = 'Client' THEN
        IF NOT EXISTS (
            SELECT 1
            FROM internal.support_users recipient
            WHERE recipient.id = NEW.client_user_id
              AND recipient.client_id = NEW.client_id
              AND recipient.status IS TRUE
              AND recipient.deactive_date IS NULL
        ) THEN
            RAISE EXCEPTION 'case notification client recipient is unavailable for tenant'
                USING ERRCODE = '23514';
        END IF;
    ELSIF NOT EXISTS (
        SELECT 1
        FROM admin.users recipient
        WHERE recipient.id = NEW.admin_user_id
          AND recipient.status IS TRUE
          AND recipient.deactive_date IS NULL
    ) THEN
        RAISE EXCEPTION 'case notification admin recipient is unavailable'
            USING ERRCODE = '23514';
    END IF;

    RETURN NEW;
END;
$function$;

CREATE TRIGGER trg_case_notifications_recipient
BEFORE INSERT OR UPDATE OF recipient_kind, admin_user_id, client_user_id, client_id
ON digital.case_notifications
FOR EACH ROW EXECUTE FUNCTION digital.enforce_case_notification_recipient();

REVOKE ALL ON TABLE digital.case_notifications FROM PUBLIC;
REVOKE ALL ON SEQUENCE digital.case_notifications_notification_id_seq FROM PUBLIC;

DO $application_role$
BEGIN
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'shovan') THEN
        GRANT INSERT, SELECT, UPDATE (read_at) ON TABLE digital.case_notifications TO shovan;
        GRANT USAGE ON SEQUENCE digital.case_notifications_notification_id_seq TO shovan;
        REVOKE DELETE, TRUNCATE ON TABLE digital.case_notifications FROM shovan;
    END IF;
END
$application_role$;

COMMENT ON TABLE digital.case_notifications IS
    'Recipient-specific Ticket/Inquiry notifications. Rows are written with the case mutation and its referenced transactional outbox event; delivery is derived only from the committed outbox.';
COMMENT ON COLUMN digital.conversation_outbox.idempotency_key IS
    'Stable producer idempotency key. It prevents duplicate durable event rows for one logical mutation.';
