-- Local/test bootstrap only; never run against the shared database.
-- Creates the minimal externally owned table shapes needed for migration validation.
-- Creates no rows and no schema_migrations ledger.

BEGIN;

DO $bootstrap_guard$
BEGIN
    IF to_regclass('digital.schema_migrations') IS NOT NULL
       OR to_regclass('digital.schema_migrations_local_backup') IS NOT NULL
       OR to_regclass('digital.pk_schema_migrations') IS NOT NULL
       OR to_regclass('digital.conversation_access') IS NOT NULL
       OR to_regclass('digital.attachments') IS NOT NULL
       OR to_regclass('digital.private_conversation_review') IS NOT NULL THEN
        RAISE EXCEPTION
            'Refusing local foundation bootstrap: a CBS Support migration object already exists';
    END IF;
END
$bootstrap_guard$;

CREATE SCHEMA IF NOT EXISTS admin;
CREATE SCHEMA IF NOT EXISTS internal;
CREATE SCHEMA IF NOT EXISTS digital;

-- Local stand-in for the externally owned administrator table.
CREATE TABLE admin.users (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    user_name text,
    full_name text,
    status boolean NOT NULL DEFAULT TRUE,
    deactive_date timestamptz,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

-- Local stand-in for the externally owned tenant table.
CREATE TABLE internal.clients (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    client_alias text,
    client_name text,
    CONSTRAINT pk_clients PRIMARY KEY (id),
    CONSTRAINT uq_clients_alias UNIQUE (client_alias),
    CONSTRAINT uq_clients_name UNIQUE (client_name)
);

-- Shape required by migration guards and participant foreign keys; no user_id.
CREATE TABLE internal.support_users (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    client_id integer NOT NULL,
    user_name text,
    full_name text,
    status boolean NOT NULL DEFAULT TRUE,
    deactive_date timestamptz,
    CONSTRAINT pk_support_users PRIMARY KEY (id),
    CONSTRAINT fk_support_users_client
        FOREIGN KEY (client_id) REFERENCES internal.clients(id)
);

-- Legacy instruction shape; external-domain foreign keys are omitted.
CREATE TABLE digital.instructions (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    datetime timestamptz NOT NULL DEFAULT now(),
    user_id integer,
    intro_id bigint,
    iden_id bigint,
    account_id bigint,
    demand_id bigint,
    inst_category_id smallint NOT NULL,
    inst_type_id smallint NOT NULL,
    instruction text,
    alert_date date,
    expiry_date date,
    instruction_id bigint,
    assigned_to integer,
    completed boolean NOT NULL DEFAULT FALSE,
    completed_by integer,
    completed_on timestamptz,
    completed_remarks text,
    status boolean NOT NULL DEFAULT TRUE,
    remarks text,
    insert_user integer,
    insert_date timestamptz NOT NULL DEFAULT now(),
    edit_user integer,
    edit_date timestamptz,
    client_id bigint,
    client_user_id bigint,
    client_auth_user_id bigint,
    service_id bigint,
    attachment_id varchar,
    inst_channel varchar,
    ip_address varchar,
    geo_location varchar,
    notification_seen_by_admin smallint,
    notification_seen_by_client smallint,
    CONSTRAINT pk_instructions PRIMARY KEY (id),
    CONSTRAINT fk_instructions_root
        FOREIGN KEY (instruction_id) REFERENCES digital.instructions(id),
    CONSTRAINT fk_instructions_insert_user
        FOREIGN KEY (insert_user) REFERENCES admin.users(id),
    CONSTRAINT fk_instructions_assigned_to
        FOREIGN KEY (assigned_to) REFERENCES admin.users(id),
    CONSTRAINT fk_instructions_completed_by
        FOREIGN KEY (completed_by) REFERENCES admin.users(id),
    CONSTRAINT fk_instructions_edit_user
        FOREIGN KEY (edit_user) REFERENCES admin.users(id)
);

COMMENT ON TABLE digital.instructions IS
    'Local/test-only legacy foundation for migration validation; not a production schema definition.';

COMMIT;
